[[XRootD]]
arch = "aarch64"
git-tree-sha1 = "d6b4bfcd1db9f33711a4c083d9d997b32d266141"
os = "macos"

    [[XRootD.download]]
    sha256 = "6e5f8702225266aad68ab6b78155a2abe134c32a98b4ef9beb6b5944f8441507"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.6.9+0/XRootD.v5.6.9.aarch64-apple-darwin.tar.gz"
[[XRootD]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9af47a05c2d90fd9b1344290b15eeff776285bc8"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "3e8c4aa3d98a5b16fa611b3d7bc47557a613c85bd4e5e3656a543038e6b1e3b4"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.6.9+0/XRootD.v5.6.9.aarch64-linux-gnu-cxx03.tar.gz"
[[XRootD]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b38108934883ffa0f8461310ddc4bc2161c8c9e6"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "fd3a26d346bd7e5aca798141ef51e096b6b97b81a1560951bc1a449a6223014f"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.6.9+0/XRootD.v5.6.9.aarch64-linux-gnu-cxx11.tar.gz"
[[XRootD]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fb4ac7a6ad8ed745249ce733b2e0d99b63a8b111"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "380709bbf727d6e9671ca57009a00dcfd2f984b65167af07b7f7b49f2488f5cc"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.6.9+0/XRootD.v5.6.9.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[XRootD]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6fc560250d2efda3a30e7bef2a9c8f149aa54196"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "61ccc01b07e9582bcef5eb0e99c9272a1b3d34d46819966a405723452daf8783"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.6.9+0/XRootD.v5.6.9.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[XRootD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "40afd63415dd6b46a7cdd83b78d9e07ffb388b3a"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "2d6e08a4c54f3b23678a53f6b24df114ee7a803a76a99cc0522138c53ec584b6"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.6.9+0/XRootD.v5.6.9.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[XRootD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d6431e43ab90429af2a2429cee4fb418d8622877"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "a0605688cb07d1435de4a5873ffd145e0c241b1e65865fea588eba0c0d14e2b1"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.6.9+0/XRootD.v5.6.9.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[XRootD]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "992a771f2237a27e4a4ff2d2d782dc2b2df5ca5a"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "75ea99943955296c271b6c527dd68477973d4633947aa5a28c408373bf32f8c6"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.6.9+0/XRootD.v5.6.9.i686-linux-gnu-cxx03.tar.gz"
[[XRootD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d4e591c112b4c38e4b9e0231e2583ad7cb0270f4"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "e17800e57d92403188c613b33e20c1d238d42593524ff9c3491084a78bee05db"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.6.9+0/XRootD.v5.6.9.i686-linux-gnu-cxx11.tar.gz"
[[XRootD]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f8716deaaa305ec64d821e758fb5912e68f64d6a"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "f508c3e28fa1ca4d12dd9e7895b100413a74640218cadbef98dbfa46d8495cf2"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.6.9+0/XRootD.v5.6.9.powerpc64le-linux-gnu-cxx03.tar.gz"
[[XRootD]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c4f370ee9fd8048f1b6105dabc77e9c466e5e348"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "c530f508f56c4cf9b323e1ba95af76ff8dc31cacd06540eea71b5d0efcd8cf07"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.6.9+0/XRootD.v5.6.9.powerpc64le-linux-gnu-cxx11.tar.gz"
[[XRootD]]
arch = "x86_64"
git-tree-sha1 = "cdd657a42af33f85bfd47865c971dfa6b17f90a9"
os = "macos"

    [[XRootD.download]]
    sha256 = "5b1ff6faeec98c4c482167ba097cdb7542d56fdb43219afbe382d1ae2ce90657"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.6.9+0/XRootD.v5.6.9.x86_64-apple-darwin.tar.gz"
[[XRootD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b1424675f3024b843a8b08c5bd1e85799456d39c"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "b813b91cd4b6fd6c0712cd56a0a6e016de2c378811a81097b9dc2214a056fd68"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.6.9+0/XRootD.v5.6.9.x86_64-linux-gnu-cxx03.tar.gz"
[[XRootD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "466229fd8fa2d6a23c2e2ee9a6bca1a761a6ad08"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "30b6df39ee6e194c4f014b65d390ec84bccf2634d5377732fce3cc98b6ca8927"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.6.9+0/XRootD.v5.6.9.x86_64-linux-gnu-cxx11.tar.gz"
