[[XRootD]]
arch = "aarch64"
git-tree-sha1 = "d7f8626a7055397045bff10d1f18132236662705"
os = "macos"

    [[XRootD.download]]
    sha256 = "42ced7a018c928074f8e906c6953d60c81fe88e6f952b3e5be3b075fb064c33f"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.7.2+0/XRootD.v5.7.2.aarch64-apple-darwin.tar.gz"
[[XRootD]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "da7c4df6d923d6ec332d76510f8772b5a54ef4dd"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "63cc5896da39ffeccbeace599781aa959501f1433b2c871fa7e20391839f3dc6"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.7.2+0/XRootD.v5.7.2.aarch64-linux-gnu-cxx03.tar.gz"
[[XRootD]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f154f8fc259071fa5643070a1b75540caa44d17f"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "3a42aca4b24eb263ef16accb3fecc520c453eac04cc2fc4c3ffa1a579abb89fb"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.7.2+0/XRootD.v5.7.2.aarch64-linux-gnu-cxx11.tar.gz"
[[XRootD]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "18b5290aca499a3ad888866c17a6853df6e5859d"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "3fd789c3e8637f2553f738862c065614bbcfe736f844f9562136caf9eed587f4"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.7.2+0/XRootD.v5.7.2.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[XRootD]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "956ad154fcb918c00b3c384713bfa8e6f3ed5cd8"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "46682ed9b1a3fc943db0e655b98401416c4a53dd09cfe44540ed201632a1cf73"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.7.2+0/XRootD.v5.7.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[XRootD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c73ab69b5e2fd016e147221dedd0c568c26619f6"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "82fc1c664ae591b526e10f5a151d6a2acc8f753674012e2699ea679d333c5207"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.7.2+0/XRootD.v5.7.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[XRootD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a759d507e67271989cf8643e68256bd02892f530"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "45fac308aea9ba950c0dccc0c3788cdcb979e4d236b8fb8a35496fbfebbf4b12"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.7.2+0/XRootD.v5.7.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[XRootD]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f1d18867b7cf5cef64ba40fd66469f38e8456497"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "1a1f6f7fa2c86935af3cfdea93ef8dd283187918e72b6b9d57b9181849d3f671"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.7.2+0/XRootD.v5.7.2.i686-linux-gnu-cxx03.tar.gz"
[[XRootD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fa0ce40247958db7e8b29046a7bad6bfb0289742"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "e31912ed90ad10d98a0bc9c3e7a24d1f70ffe627441d54a5038a02c153172000"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.7.2+0/XRootD.v5.7.2.i686-linux-gnu-cxx11.tar.gz"
[[XRootD]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7853b223622364ddb5867cdcecb5703ab9bde7d9"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "77cd140c7df1a2e60ee17f7e9ec1c81881857dffa024ed3a8b33e2471b3db2fe"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.7.2+0/XRootD.v5.7.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[XRootD]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5d565e779de3b4a87c8fbad1529706697bd22fd7"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "eaf3cd9589bb18c9fb12054ce0de667ad6fd0a52b99049e7045a4cfb047d776a"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.7.2+0/XRootD.v5.7.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[XRootD]]
arch = "x86_64"
git-tree-sha1 = "f5fcbf19a2631b81ab2d8e3f62b0b38e8af5fb09"
os = "macos"

    [[XRootD.download]]
    sha256 = "f15e33301222b554dbe8feefa28b171886dbd917ff203cd4f4ff8bf63e58418c"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.7.2+0/XRootD.v5.7.2.x86_64-apple-darwin.tar.gz"
[[XRootD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d7e9fde22fb3a416926e5d0b2586c6c0eb57c4de"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "a7e52e022ba2a6074addaef2d574fabc021fdf26e81eb88da4630d77b5b57d1c"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.7.2+0/XRootD.v5.7.2.x86_64-linux-gnu-cxx03.tar.gz"
[[XRootD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eda747e91b233c1afad1360643b4e00b3f5594d5"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "5bc9e93295c96dd3f5263252391cb18b1c5cf0d97f854270c164c348b70f321c"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.7.2+0/XRootD.v5.7.2.x86_64-linux-gnu-cxx11.tar.gz"
