[[XRootD]]
arch = "aarch64"
git-tree-sha1 = "8520a52585f5eadf78b58f2d486d1abb34f514f1"
os = "macos"

    [[XRootD.download]]
    sha256 = "0e89dab93b6d60e810443cdc5a75dc4e0aa7234d2db768bdd8ff58164fce0994"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.7.1+0/XRootD.v5.7.1.aarch64-apple-darwin.tar.gz"
[[XRootD]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "18b8ce878af58e3b720affda8c3025b2cd8ca9a5"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "dea4f0382e1d1e40e024f04677bf96f173d6d13d3523085a24a12c5863df8432"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.7.1+0/XRootD.v5.7.1.aarch64-linux-gnu-cxx03.tar.gz"
[[XRootD]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "550d4d829295f5106b6a4810d44fdf0abfcf7017"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "d353bee21f4f68e61cdba4e3697fb0f13e7cb5677bef86e15a1638e5d8f5e626"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.7.1+0/XRootD.v5.7.1.aarch64-linux-gnu-cxx11.tar.gz"
[[XRootD]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9f15051b620669b95626901da96430c778c0e33f"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "98d1b79957171c38606f0994f3993108b6b6d30e14066651cce83b94dcda4b1b"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.7.1+0/XRootD.v5.7.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[XRootD]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c38e1d16f4ef99746912d3ed449c5c6b5e3ef9a6"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "5edd4aed66ea001dbe23b420611f1d21ffeb5002f0e07800a4a4553072c8138b"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.7.1+0/XRootD.v5.7.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[XRootD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "87c766223de9a6c0f68914d0bb985af6a789f4ab"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "6c3488913ec7a7659ccd91571b0ee09294998cae24bbb0b32e96a1649fbf0d42"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.7.1+0/XRootD.v5.7.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[XRootD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "495f9855f0cf4bffc183f874b37db953cef1e158"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "154ba48193c15aca1ac3072f0b38ce5834d577086dc38698d59b9cc440dfe2b6"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.7.1+0/XRootD.v5.7.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[XRootD]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d318e8056b7f55f2f4f4b1edb12190d8c4a82fbd"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "6d836a03ee3601de1f09bf2a72017110ef2cc1ce3db51fdcd6f3dc3b372565f0"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.7.1+0/XRootD.v5.7.1.i686-linux-gnu-cxx03.tar.gz"
[[XRootD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6d8af6e1315d4e111bfd46e56c15309a53c93a2c"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "27850e092883735d36520911395ce0b57ee253ec64e1a776fc3eea1dbd2d8b75"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.7.1+0/XRootD.v5.7.1.i686-linux-gnu-cxx11.tar.gz"
[[XRootD]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "09357d9f531aaafba2cb354055dfc09657bdf6f7"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "21d80b040af1c6d99fb7b0c3fb0472fcc2237542880289508476fb37ddeafdee"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.7.1+0/XRootD.v5.7.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[XRootD]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2463a6787ec26ff33a27c78adc58ed174822b726"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "05ba10cf4d6d079175b6670de10725257eeaebd9896cfb739e3a8add48bf2878"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.7.1+0/XRootD.v5.7.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[XRootD]]
arch = "x86_64"
git-tree-sha1 = "b9bb3f7b04f8c312f888a26c4b830e5bf69f799b"
os = "macos"

    [[XRootD.download]]
    sha256 = "e8ce6d629a0fdfb06a0d628b7f5a8abbefcf2a241fa849eb3f09937ec9f4608c"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.7.1+0/XRootD.v5.7.1.x86_64-apple-darwin.tar.gz"
[[XRootD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "34ab28e2557764e749836a6c023b6022d94a5a37"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "6827bc93fa8ec7f171374e3076c75e2f0781c5ad77967f6d928422599d8805a7"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.7.1+0/XRootD.v5.7.1.x86_64-linux-gnu-cxx03.tar.gz"
[[XRootD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d17e52e6f1547d49daa3893eb1753a9cccdc236"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "c548de6979f8ce935ee9ba1fe0ffab142e60064eb24bbf12c03ee7ce4566209f"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.7.1+0/XRootD.v5.7.1.x86_64-linux-gnu-cxx11.tar.gz"
