[[XRootD]]
arch = "aarch64"
git-tree-sha1 = "bfadb368bfee6bcb3d8547d58203cf0b61732b9c"
os = "macos"

    [[XRootD.download]]
    sha256 = "8bd023a79c70a6ebf6f202c94aa35a048f909474adcb1832e47a27f6e7738527"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.8.4+0/XRootD.v5.8.4.aarch64-apple-darwin.tar.gz"
[[XRootD]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "954ee88c13a9016fd4d53baffb238f84f4f27e1e"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "832dd0ef4223c29fed53dd4716ec3821dd5dc2aabd5ceaf2ea7e243976b149f7"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.8.4+0/XRootD.v5.8.4.aarch64-linux-gnu-cxx03.tar.gz"
[[XRootD]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6a97cd97ddf7a072412b40e629de9a5d8b97432d"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "0047f9d7f900d8996f3c20acf6b84bd75980da2805925152e44e3c768389d37e"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.8.4+0/XRootD.v5.8.4.aarch64-linux-gnu-cxx11.tar.gz"
[[XRootD]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "61362c08d122df4082b207ad7d81a89a2b1e7912"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "19fb8c7109bcbd24c7008f870cdf692f84b751997a6d2f0ea3a610099774eb3a"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.8.4+0/XRootD.v5.8.4.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[XRootD]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "787c4a5d248ff849a54c8e9d9dd04c4dd79f9f14"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "a5ea5dd11eb85442c64c3b9e79ba23eb655248a4a84baf4278e3b6394e86caa5"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.8.4+0/XRootD.v5.8.4.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[XRootD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "278676d14537619cc193480d5cad97cabe6f4e80"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "30cc79c891b2ba1f00e84861c40de50fd5592c6f66d70634c9c1084685f44334"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.8.4+0/XRootD.v5.8.4.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[XRootD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b2b181a1d88cc35ca71141e173abdf63127fec2a"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "69e1d18b97ee4a1ec91b9ddfe483736165cfb59a995f006aeae45f673c092420"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.8.4+0/XRootD.v5.8.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[XRootD]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8dc30f8c944eec2993e8ac6338c8df65922e698b"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "0195792ce885e24c201bdebb6bc7b64f25e9ed6a93dce6ea1a2c1d73621e1382"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.8.4+0/XRootD.v5.8.4.i686-linux-gnu-cxx03.tar.gz"
[[XRootD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c14b66a6ec7d3f02e9c86d10c3754be694690d18"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "40f92a8580e4089135ebbff133917262a9405bb599668f6143c60f22286f9bb6"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.8.4+0/XRootD.v5.8.4.i686-linux-gnu-cxx11.tar.gz"
[[XRootD]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d6097ce76e636749fe0125ed147257ed781a2a6f"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "1c4c386ed6b01ea7917b2ee6333f64b59afa791ea77ce13b3ecc190ca09c9947"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.8.4+0/XRootD.v5.8.4.powerpc64le-linux-gnu-cxx03.tar.gz"
[[XRootD]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f07272945059cb082b339ebb773780485d881d5d"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "bb80e0043dae24ef149d68c68e9103f25509851eaa5643a7877c9a9235b3e415"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.8.4+0/XRootD.v5.8.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[XRootD]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d4cbb7245b3fb4b810b286f2d33a066c4fedb331"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "ec1734fd49d03c6528f0c6745c981edf4e9aac5a4a1c46b38e1833fac691bec8"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.8.4+0/XRootD.v5.8.4.riscv64-linux-gnu-cxx03.tar.gz"
[[XRootD]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0369611f35ca9224d010af436e7f2f29dc4af157"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "670c7aeecc3b766cc1806d8f34ff54497e3be1729769692d6436a21b529c407b"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.8.4+0/XRootD.v5.8.4.riscv64-linux-gnu-cxx11.tar.gz"
[[XRootD]]
arch = "x86_64"
git-tree-sha1 = "16437827190c0cee0c26b3c0ce4509b1d81b9262"
os = "macos"

    [[XRootD.download]]
    sha256 = "21e24c01bd7dcdd0603beb4cc20857d742d577edfea067436cea36aae6871b1d"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.8.4+0/XRootD.v5.8.4.x86_64-apple-darwin.tar.gz"
[[XRootD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a916314e395d319c6ae779f306132130d7f1248c"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "a2e0656375f79bd6dbc9b3e71d97814f23438d964898afab6cc1db52404ea6ae"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.8.4+0/XRootD.v5.8.4.x86_64-linux-gnu-cxx03.tar.gz"
[[XRootD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "488221b3fac0f367a928da41b37395bdeb9f5f5e"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "bd8cefc49cfd26466c067460239e33ebfcd1f2610358a710b13950371232f986"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.8.4+0/XRootD.v5.8.4.x86_64-linux-gnu-cxx11.tar.gz"
