[[XRootD]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "553964337beafa3c773cbeadb3de2147a2236afa"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "5263f1062a7e6964671f2d7f275237e7d4ab429156e972efb7071293be5b4253"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.5.4+0/XRootD.v5.5.4.aarch64-linux-gnu-cxx03.tar.gz"
[[XRootD]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e81a6bedd956399cbdb03d981ca417c40e40248"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "be2cfecc08ca2aa4e6529205733031d67e08f8373efa6dc2b94db73613bfbaae"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.5.4+0/XRootD.v5.5.4.aarch64-linux-gnu-cxx11.tar.gz"
[[XRootD]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "237b8d96ec528e41e299c5b37405717194b70974"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "e9da835c50c6307d6d3b889c4ba51eee79492d43d0781619407f35af136a9682"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.5.4+0/XRootD.v5.5.4.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[XRootD]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "777cd1efdf9f321a89fa4e70e75cfe9b9f3184ca"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "5b17ad15c771eaf940f9040139de00c4211c4609377bbecd34430caf781af200"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.5.4+0/XRootD.v5.5.4.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[XRootD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6684f6131182cdaeb5fbc81658e1c22a94a762e8"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "4041005bae92bdf4d258fb57e5c62ae053fa418245f26f463c908efd08e590b3"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.5.4+0/XRootD.v5.5.4.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[XRootD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8aecde168c0b94995608917df18d009aa3dc5c3c"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "9faeac9256c8f99325db348817e3452d42c9aac486bf60ab5650642d10d2a52f"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.5.4+0/XRootD.v5.5.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[XRootD]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "51f520ad3c89b2c7792fd46ef86ac775b32ec454"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "ab251522e4e03091a21fdb2b58a7eb60cafb42bf571eb9d5401d56d0426ed87f"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.5.4+0/XRootD.v5.5.4.i686-linux-gnu-cxx03.tar.gz"
[[XRootD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e56a934b0cf519d69782905e8b801b4edd6d3d1a"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "f3fcd0a2432ebae5a9397459d2a722dcd930fe3c70038eacf8e90b2d53fd73bd"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.5.4+0/XRootD.v5.5.4.i686-linux-gnu-cxx11.tar.gz"
[[XRootD]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d348095d8c10a7ae5c2745fec7d112a93c07f353"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "f944707dbada1cc51d1ee1f6011ee1cb71e5d53c14bd3d45026d12191c55a302"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.5.4+0/XRootD.v5.5.4.powerpc64le-linux-gnu-cxx03.tar.gz"
[[XRootD]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4cffeea857b17c467c22829be46d4b23515df2bf"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "91c155f9100dbe287db0c447e21ae261b79561f27f5585da9cd5b6ef0c9188a9"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.5.4+0/XRootD.v5.5.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[XRootD]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1894dc8f7715595faecf84ad9bc2e74935005794"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "6c441ea6ef9eb17f12ba6657cc33242b349e16958ab5e2bc6e11700c77683032"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.5.4+0/XRootD.v5.5.4.x86_64-linux-gnu-cxx03.tar.gz"
[[XRootD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4bdb85f643aee610af6fa2aacad190241b956899"
libc = "glibc"
os = "linux"

    [[XRootD.download]]
    sha256 = "742e430d2ed1b439d0b264167932d79b97ba179b4d215df9722237a39b7af97c"
    url = "https://github.com/JuliaBinaryWrappers/XRootD_jll.jl/releases/download/XRootD-v5.5.4+0/XRootD.v5.5.4.x86_64-linux-gnu-cxx11.tar.gz"
